### ISSUE TITLE
drop element identifier

### ISSUE THREAD

**Issue by sivi** [neoziro/angular-draganddrop#12]
It would be great to be able to identify target element which receives the data (e.g. editing trees). HTML directive perhaps e.g.:

 &lt; div drop="onDrop($data, $event, $dropIdentifier)"
 drop-identifier="{node: {{node.nodeId}}}"
 drop-effect="link"
 drop-accept="'json/image'"
 drag-over="onDragOver($event)"
 drag-over-class="drag-over"></div>

In the code it would require adding

var dropIdentifier = scope.$eval(attrs.dropIdentifier);

in list of dropDirective, and expand {$data: data, $event: event} with passed identifier, e.g.

        // Call dropHandler
        scope.$apply(function () {
          var dropParams = {$data: data, $event: event,  $dropIdentifier: dropIdentifier};
          dropHandler(scope, dropParams);
        });

**Comment by neoziro** [comment]
@sivi you must do it manually, this directive is generic by choice.
