### ISSUE TITLE
locating payload may be easier

### ISSUE THREAD

**Issue by sivi** [neoziro/angular-draganddrop#13]
If draggableDirective would include 

 e.dataTransfer.setData('draggableType', draggableType);

it would be much easier locate payload i user's code:
    var draggableType = $event.dataTransfer.getData('draggableType');
    var payloadData = JSON.parse($event.dataTransfer.getData('json/' + draggableType));

**Comment by neoziro** [comment]
@sivi I am sorry but it's not the philosophy of HTML5 drag and drop API, you can do it by yourself if you want
