### ISSUE TITLE
Minified script downloads unminified script?

### ISSUE THREAD

**Issue by CraigWarford** [neoziro/angular-draganddrop#5]
Okay, maybe I'm losing it, but I added only the minified script to my page (unminified was *never* added), and yet, that script seems to be attempting to load the unminified script, so that both end up getting loaded...  If I rename the unminified file on the server, I get a 404 error.

**Comment by neoziro** [comment]
@CraigWarford hmm I am sorry but the script doesn't load any script, you just have to load the minified or unminified script according your choice. You are probably doing something wrong but I can't help you really here.. Sorry.
