### ISSUE TITLE
drop-accept should have $data as parameter instead of $type

### ISSUE THREAD

**Issue by stefan-schweiger** [neoziro/angular-draganddrop#6]
you can get the type from the data. also you would be able to check if the $data is already in your drop area and therefore deny being dropped again.

**Comment by neoziro** [comment]
Your issue is probably solved, sorry for the delay, I close it.

**Comment by stefan-schweiger** [comment]
While I just went with using a different "extension" for drag and drop, I still think think it would make more sense to have $data as parameter instead of $type (as you can get the type from the data anyways but not vice versa), but it's not like I really care anymore ;)
